##############################################
# Integration test setup for the GH workflow #
##############################################

version: "3.9"
services:

  tmm-api:
    image: ${TMM_API_IMAGE_NAME}
    depends_on:
      - influx
    environment:
      INFLUX_CONFIG_FILE: /run/secrets/tmm_influx_config      
      TMM_BUCKET_FILE: /run/secrets/tmm_bucket
      TMM_API_KEY_FILE: /run/secrets/tmm_api_key
    secrets:
      - tmm_influx_config
      - tmm_bucket
      - tmm_api_key
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

  influx:
    image: influxdb:2.2.0-alpine
    ports:
      - "8086:8086"
    env_file:
      - ./influx_docker.env
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    depends_on:
      - tmm-api
    volumes:
      - nginx_config:/etc/nginx/
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
  
secrets:
  tmm_influx_config: 
    external: true
  tmm_bucket:
    external: true
  tmm_api_key:
    external: true

volumes:
  nginx_config:
    external: true