version: "3.9"
services:
  tmm:
    build: services/web
    env_file:
      - .dev.env    
    ports:
      - "5000:5000"
  influx:
    image: influxdb:2.2.0-alpine
    volumes:
      - influxdb-storage:/var/lib/influxdb
    ports:
      - "8086:8086"
    env_file:
      - .dev.env    

volumes:
  influxdb-storage: {}
