version: "3.9"
services:
  tmm-api:
    image: tmm-api
    depends_on:
      - influx
    env_file:
      - .dev.env
    environment:
      INFLUX_CONFIG_FILE: /run/secrets/influx_config
    secrets:
      - influx_config
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
  influx:
    image: influxdb:2.2.0-alpine
    ports:
      - "8086:8086"
    env_file:
      - .dev.env
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure


secrets:
  influx_config: 
    file: ./examples/influx_config.ini