version: "3.9"
services:

  tmm-api:
    image: ${TMM_API_IMAGE_NAME}
    pull_policy: always
    environment:
      INFLUX_CONFIG_FILE: /prod_tmm_influx_config/influx_config.ini
      TMM_BUCKET: ${TMM_BUCKET}
      PORT: 5005
    ports:
      - "5005:5005"
    volumes:
      - prod_tmm_influx_config:/prod_tmm_influx_config:ro

volumes:
  prod_tmm_influx_config:
    external: true
