[tool.poetry]
name = "tmm-api"
version = "0.1.0"
description = "Teuto Moisture Map Api"
authors = ["code4bielefeld"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
influxdb-client = "^1.31.0"
Flask = "^2.2.2"
jsonpath-ng = "^1.5.3"
gunicorn = "^20.1.0"
Flask-Cors = "^3.0.10"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
mypy = "^0.982"
ruff = "^0.0.99"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]

[tool.ruff]
line-length = 120
select = [
    "C","E","F","W","B","Q", "N","U"
    #,"D" # todo
    ]
ignore = ["E501"]
exclude = [
    ".git",
    "__pycache__",
    "*.egg-info",
    ".nox",
    ".pytest_cache",
    ".mypy_cache"
    ]

[tool.black]
line-length = 120