[tool.poetry]
name = "tmm-api"
version = "0.1.0"
description = "Teuto Moisture Map Api"
authors = ["code4bielefeld"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
influxdb-client = "^1.31.0"
Flask = "^2.2.2"
jsonpath-ng = "^1.5.3"
gunicorn = "^20.1.0"
pytest = "^7.1.2"

[tool.poetry.dev-dependencies]
autopep8 = "^1.7.0"
flake8 = "^5.0.4"
flake8-bugbear = "^22.9.23"
black = "^22.10.0"
mypy = "^0.982"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
