name: Checks for dwd-import service
on: [push]
jobs:
  nox:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Nox
        uses: daisylb/setup-nox@v2.1.0      
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry config virtualenvs.prefer-active-python true      
      - name: Run nox for service dwd-import
        working-directory: ./services/dwd-import
        run: nox
