name: Build the tmm-api service

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  STACK_NAME: tmm-api

jobs:
  build-tmm:
    runs-on: ubuntu-latest
    outputs:
      GITHUB_SHA_SHORT: ${{ steps.sha7.outputs.GITHUB_SHA_SHORT }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get short SHA
        id: sha7
        run: |
          GITHUB_SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA_SHORT}" >> $GITHUB_ENV
          echo "::set-output name=GITHUB_SHA_SHORT::${GITHUB_SHA_SHORT}"
      - name: Build image
        uses: mamezou-tech/buildpacks-action@master
        with:
          image: ${REGISTRY}/${IMAGE_NAME}/django-app
          tag: ${GITHUB_SHA_SHORT}
          path: 'services/tmm-api'
          builder: 'gcr.io/paketo-buildpacks/builder:base'
      - run: echo "🍏 This job's status is ${{ job.status }}."