name: Build the tmm-api service

on: [push]

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  STACK_NAME: tmm-api

jobs:
  tmm-build:
    runs-on: ubuntu-latest
    outputs:
      GITHUB_SHA_SHORT: ${{ steps.sha7.outputs.GITHUB_SHA_SHORT }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get short SHA
        id: sha7
        run: |
          GITHUB_SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA_SHORT}" >> $GITHUB_ENV
          echo "::set-output name=GITHUB_SHA_SHORT::${GITHUB_SHA_SHORT}"
      - name: Build image
        uses: mamezou-tech/buildpacks-action@master
        with:
          image: ${REGISTRY}/${REPOSITORY}/${STACK_NAME}
          tag: ${GITHUB_SHA_SHORT}
          path: 'services/tmm-api'
          builder: 'gcr.io/paketo-buildpacks/builder:base'      
      - name: Start service
        run: docker-compose -f docker-compose.int.yaml up -d
      - name: Check service
        run: |
          sleep 10
          curl -f localhost:5000/internal/health/self
          curl -f localhost:5000/internal/health/int
      - name: Service Logs
        if: failure()
        run: docker-compose -f docker-compose.int.yaml logs
      - name: Stop service
        if: always()
        run: docker-compose -f docker-compose.int.yaml down

